services:
  mongo:
    image: mongo:7
    container_name: inventory-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inventory
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: inventory-app
    restart: always
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/inventory
      SESSION_SECRET: supersecret
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo_data:
